### ISSUE TITLE
-

### ISSUE THREAD

**Issue by cuj** [cirosantilli/test-asciidoc-large-variable#1]
>

**Comment by cirosantilli** [comment]
I saw the 500 now, it is quite intermittent.

```
= h
:var: abc

{var}
```

in asciidoctor should render as:

```
<h1>h

<p>abc
```

so I was trying to create a huge variable to see if things blow up.

Github runs Asciidoctor quite natively, so any adoc blowups lead to 500s, e.g. a previous one; https://twitter.com/cirosantilli/status/1283339613814370304

I forgot why these specific sizes were chosen. You can't just pick arbitrarily large because github cuts up file rendering at 512 KB: https://github.com/isaacs/github/issues/1610 so pointless going beyond that.

**Comment by cirosantilli** [comment]
OK, remembered now, it was close to optimum, you have to optimize `f(x, y)` with `x + 3y = 512KiB`. Exact result is `x = 256KiB` and y = 512Kib/6`. Previous script just did `512Kib/8` to stay in power of 2. I got it closer to the limit now with `85 * (2 ** 10)`.

We have to see if it is possible to add HTML in the variable. Then we can make the output much larger even. ( as it stands, out of memory killer already kills it on my Linux machine). Edit, didn't work:

```
= h
:a: *c*

{a}{a}{a}
```

does not expand `*` into `<i>`.

**Comment by cirosantilli** [comment]
(I don't understand why sometimes GitHub does not try to render and shows just the plaintext and does not blow up. For some reason `2 ** 15` blows more often.)

**Comment by cuj** [comment]
Hi cirosantilli, please delete this issue. closing is not enough. I want my issue to be deleted. Thank you

**Comment by cuj** [comment]
And please delete all of my issues under cirosantilli/test-git-web-interface. Thanks @cirosantilli

**Comment by cirosantilli** [comment]
Can I ask why? Why not delete account and re-create it instead with same handle for example, so that everything goes to ghost?
